# eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka:
      instance:
        hostname: localhost
      client:
        service-url:
          defaultZone: http://host.docker.internal:8761/eureka
